language: ruby
rvm:
  - 2.2.10
  - 2.3.7
  - 2.4.4
  - 2.5.1
  - ruby-head
  - jruby-head
env:
  - "ACTIVE_RECORD_VERSION=4.2"
  - "ACTIVE_RECORD_VERSION=~5.0"
  - "ACTIVE_RECORD_VERSION=~5.1"
  - "ACTIVE_RECORD_VERSION=~5.2"
  - "ACTIVE_RECORD_VERSION=master"
matrix:
  allow_failures:
    - env: "ACTIVE_RECORD_VERSION=master"
    - rvm: ruby-head
    - rvm: jruby-head
sudo: false
