language: ruby
rvm:
  - 2.2.2
  - 2.3.0
  - ruby-head
  - jruby-head
env:
  - "ACTIVE_RECORD_VERSION=4.2.0"
  - "ACTIVE_RECORD_VERSION=~5.0.0"
  - "ACTIVE_RECORD_VERSION=master"
matrix:
  allow_failures:
    - env: "ACTIVE_RECORD_VERSION=master"
    - rvm: ruby-head
    - rvm: jruby-head
sudo: false
